// src/pages/Settings/index.tsx
import React, {
  ReactElement,
  useCallback,
  useEffect,
  useMemo,
  useState,
} from 'react';
import { Trans, useTranslation } from 'react-i18next';
import {
  LuAudioLines,
  LuBookmark,
  LuBrain,
  LuCog,
  LuCpu,
  LuDatabase,
  LuFilter,
  LuFlaskConical,
  LuGrid2X2Plus,
  LuHand,
  LuMessageCircleMore,
  LuMessagesSquare,
  LuMonitor,
  LuRefreshCw,
  LuRocket,
  LuSettings,
  LuSpeech,
  LuVolume2,
  LuVolumeX,
} from 'react-icons/lu';
import { useNavigate } from 'react-router';
import { Button, Dropdown, Icon } from '../../components';
import { CONFIG_DEFAULT, INFERENCE_PROVIDERS } from '../../config';
import { useDebouncedCallback } from '../../hooks/useDebouncedCallback';
import TextToSpeech, {
  getSpeechSynthesisVoiceByName,
  getSpeechSynthesisVoices,
  IS_SPEECH_SYNTHESIS_SUPPORTED,
} from '../../hooks/useTextToSpeech';
import { SUPPORTED_LANGUAGES } from '../../i18n';
import { useAppContext } from '../../store/app';
import { useChatContext } from '../../store/chat';
import { useInferenceContext } from '../../store/inference';
import { useModals } from '../../store/modal';
import {
  Configuration,
  ConfigurationKey,
  InferenceApiModel,
  InferenceProvidersKey,
  ProviderOption,
} from '../../types';
import {
  DropdownOption,
  SettingField,
  SettingFieldCustom,
  SettingFieldDropdown,
  SettingFieldInput,
  SettingFieldInputType,
  SettingInputType,
  SettingSection,
  SettingTab,
} from '../../types/settings';
import { classNames } from '../../utils/css-helpers';
import { isBoolean, isNumeric, isString } from '../../utils/type-guards';
import {
  DelimeterComponent,
  ImportExportComponent,
  PresetManager,
  SettingsModalCheckbox,
  SettingsModalDropdown,
  SettingsModalLongInput,
  SettingsModalRangeInput,
  SettingsModalShortInput,
  SettingsSectionLabel,
  ThemeController,
} from './components';

// --- Constants ---
const DELIMITER: SettingFieldCustom = {
  type: SettingInputType.CUSTOM,
  key: 'custom',
  component: 'delimeter',
};

// --- Helper Functions ---
function toSection(
  label: string | ReactElement,
  icon?: string | ReactElement
): SettingSection {
  return {
    type: SettingInputType.SECTION,
    label: (
      <>
        {icon}
        {label}
      </>
    ),
  };
}

function toInput(
  type: SettingFieldInputType,
  key: ConfigurationKey,
  disabled: boolean = false,
  additional?: Record<string, unknown>
): SettingFieldInput {
  return {
    type,
    disabled,
    key,
    ...additional,
  };
}

function toDropdown(
  key: ConfigurationKey,
  options: DropdownOption[],
  filterable: boolean = false,
  disabled: boolean = false
): SettingFieldDropdown {
  return {
    type: SettingInputType.DROPDOWN,
    key,
    disabled,
    options,
    filterable,
  };
}

// --- Setting Tabs Configuration ---
function getSettingTabsConfiguration(
  config: Configuration,
  models: InferenceApiModel[],
  t: ReturnType<typeof useTranslation>['t']
): SettingTab[] {
  return [
    /* General */
    {
      title: (
        <>
          <Icon size="sm" variant="leftside">
            <LuSettings />
          </Icon>
          {t('settings.tabs.general')}
        </>
      ),
      fields: [
        toSection(t('settings.sections.inferenceProvider')),
        toDropdown(
          'provider',
          Object.entries(INFERENCE_PROVIDERS).map(
            ([key, val]: [string, ProviderOption]) => ({
              value: key,
              label: val.name,
              icon: val.icon,
            })
          )
        ),
        toInput(
          SettingInputType.SHORT_INPUT,
          'baseUrl',
          !INFERENCE_PROVIDERS[config.provider]?.allowCustomBaseUrl
        ),
        toInput(SettingInputType.SHORT_INPUT, 'apiKey'),
        toDropdown(
          'model',
          models.map((m) => ({
            value: m.id,
            label: m.name,
          })),
          true
        ),
        {
          type: SettingInputType.CUSTOM,
          key: 'fetch-models',
          component: () => null,
        },

        DELIMITER,
        DELIMITER,
        toInput(SettingInputType.LONG_INPUT, 'systemMessage'),
      ],
    },

    /* UI */
    {
      title: (
        <>
          <Icon size="sm" variant="leftside">
            <LuMonitor />
          </Icon>
          {t('settings.tabs.ui')}
        </>
      ),
      fields: [
        toSection(
          t('settings.sections.userInterface'),
          <Icon size="sm" variant="leftside">
            <LuMonitor />
          </Icon>
        ),
        toInput(SettingInputType.SHORT_INPUT, 'initials'),
        {
          type: SettingInputType.CUSTOM,
          key: 'language',
          component: () => null,
        },
        {
          type: SettingInputType.CUSTOM,
          key: 'theme-manager',
          component: () => null,
        },
        toInput(SettingInputType.CHECKBOX, 'showRawUserMessage'),
        toInput(SettingInputType.CHECKBOX, 'showRawAssistantMessage'),
      ],
    },

    /* Voice */
    {
      title: (
        <>
          <Icon size="sm" variant="leftside">
            <LuAudioLines />
          </Icon>
          {t('settings.tabs.voice')}
        </>
      ),
      fields: [
        /* Text to Speech */
        toSection(
          t('settings.sections.textToSpeech'),
          <Icon size="sm" variant="leftside">
            <LuSpeech />
          </Icon>
        ),
        toDropdown(
          'ttsVoice',
          !IS_SPEECH_SYNTHESIS_SUPPORTED
            ? []
            : getSpeechSynthesisVoices().map((voice) => ({
                value: `${voice.name} (${voice.lang})`,
                label: `${voice.name} (${voice.lang})`,
              })),
          true
        ),
        toInput(
          SettingInputType.RANGE_INPUT,
          'ttsPitch',
          !IS_SPEECH_SYNTHESIS_SUPPORTED,
          {
            min: 0,
            max: 2,
            step: 0.5,
          }
        ),
        toInput(
          SettingInputType.RANGE_INPUT,
          'ttsRate',
          !IS_SPEECH_SYNTHESIS_SUPPORTED,
          {
            min: 0.5,
            max: 2,
            step: 0.5,
          }
        ),
        toInput(
          SettingInputType.RANGE_INPUT,
          'ttsVolume',
          !IS_SPEECH_SYNTHESIS_SUPPORTED,
          {
            min: 0,
            max: 1,
            step: 0.25,
          }
        ),
        {
          type: SettingInputType.CUSTOM,
          key: 'custom', // dummy key, won't be used
          component: () => (
            <TextToSpeech
              text={t('settings.textToSpeech.check.text')}
              voice={getSpeechSynthesisVoiceByName(config.ttsVoice)}
              pitch={config.ttsPitch}
              rate={config.ttsRate}
              volume={config.ttsVolume}
            >
              {({ isPlaying, play, stop }) => (
                <Button
                  onClick={() => (!isPlaying ? play() : stop())}
                  disabled={!IS_SPEECH_SYNTHESIS_SUPPORTED}
                  title="Play test message"
                  aria-label="Play test message"
                >
                  {!isPlaying && (
                    <Icon size="sm" variant="leftside">
                      <LuVolume2 />
                    </Icon>
                  )}
                  {isPlaying && (
                    <Icon size="sm" variant="leftside">
                      <LuVolumeX />
                    </Icon>
                  )}
                  {t('settings.textToSpeech.check.label')}
                </Button>
              )}
            </TextToSpeech>
          ),
        },
      ],
    },

    /* Conversations */
    {
      title: (
        <>
          <Icon size="sm" variant="leftside">
            <LuMessagesSquare />
          </Icon>
          {t('settings.tabs.conversations')}
        </>
      ),
      fields: [
        toSection(
          t('settings.sections.chat'),
          <Icon size="sm" variant="leftside">
            <LuMessageCircleMore />
          </Icon>
        ),
        toInput(SettingInputType.SHORT_INPUT, 'pasteLongTextToFileLen'),
        toInput(SettingInputType.CHECKBOX, 'pdfAsImage'),

        /* Performance */
        DELIMITER,
        toSection(
          t('settings.sections.performance'),
          <Icon size="sm" variant="leftside">
            <LuRocket />
          </Icon>
        ),
        toInput(SettingInputType.CHECKBOX, 'showTokensPerSecond'),

        /* Reasoning */
        DELIMITER,
        toSection(
          t('settings.sections.reasoning'),
          <Icon size="sm" variant="leftside">
            <LuBrain />
          </Icon>
        ),
        toInput(SettingInputType.CHECKBOX, 'showThoughtInProgress'),
        toInput(SettingInputType.CHECKBOX, 'excludeThoughtOnReq'),
      ],
    },

    /* Presets */
    {
      title: (
        <>
          <Icon size="sm" variant="leftside">
            <LuBookmark />
          </Icon>
          {t('settings.tabs.presets')}
        </>
      ),
      fields: [
        {
          type: SettingInputType.CUSTOM,
          key: 'preset-manager',
          component: () => null,
        },
      ],
    },

    /* Import/Export */
    {
      title: (
        <>
          <Icon size="sm" variant="leftside">
            <LuDatabase />
          </Icon>
          {t('settings.tabs.importExport')}
        </>
      ),
      fields: [
        {
          type: SettingInputType.CUSTOM,
          key: 'import-export',
          component: () => null,
        },
      ],
    },

    /* Advanced */
    {
      title: (
        <>
          <Icon size="sm" variant="leftside">
            <LuGrid2X2Plus />
          </Icon>
          {t('settings.tabs.advanced')}
        </>
      ),
      fields: [
        /* Generation */
        toSection(
          t('settings.sections.generation'),
          <Icon size="sm" variant="leftside">
            <LuCog />
          </Icon>
        ),
        toInput(SettingInputType.CHECKBOX, 'overrideGenerationOptions'),
        ...['temperature', 'top_k', 'top_p', 'min_p', 'max_tokens'].map((key) =>
          toInput(
            SettingInputType.SHORT_INPUT,
            key as ConfigurationKey,
            !config['overrideGenerationOptions']
          )
        ),

        /* Samplers */
        DELIMITER,
        toSection(
          t('settings.sections.samplers'),
          <Icon size="sm" variant="leftside">
            <LuFilter />
          </Icon>
        ),
        toInput(SettingInputType.CHECKBOX, 'overrideSamplersOptions'),
        ...[
          'samplers',
          'dynatemp_range',
          'dynatemp_exponent',
          'typical_p',
          'xtc_probability',
          'xtc_threshold',
        ].map((key) =>
          toInput(
            SettingInputType.SHORT_INPUT,
            key as ConfigurationKey,
            !config['overrideSamplersOptions']
          )
        ),

        /* Penalties */
        DELIMITER,
        toSection(
          t('settings.sections.penalties'),
          <Icon size="sm" variant="leftside">
            <LuHand />
          </Icon>
        ),
        toInput(SettingInputType.CHECKBOX, 'overridePenaltyOptions'),
        ...[
          'repeat_last_n',
          'repeat_penalty',
          'presence_penalty',
          'frequency_penalty',
          'dry_multiplier',
          'dry_base',
          'dry_allowed_length',
          'dry_penalty_last_n',
        ].map((key) =>
          toInput(
            SettingInputType.SHORT_INPUT,
            key as ConfigurationKey,
            !config['overridePenaltyOptions']
          )
        ),

        /* Custom */
        DELIMITER,
        toSection(
          t('settings.sections.custom'),
          <Icon size="sm" variant="leftside">
            <LuCpu />
          </Icon>
        ),
        toInput(SettingInputType.LONG_INPUT, 'custom'),
      ],
    },

    /* Experimental */
    {
      title: (
        <>
          <Icon size="sm" variant="leftside">
            <LuFlaskConical />
          </Icon>
          <Trans i18nKey="settings.sections.experimental" />
        </>
      ),
      fields: [
        {
          type: SettingInputType.CUSTOM,
          key: 'custom', // dummy key, won't be used
          component: () => (
            <div
              className="flex flex-col gap-2 mb-8"
              dangerouslySetInnerHTML={{
                __html: t('settings.parameters.experimental.note'),
              }}
            />
          ),
        },
        toInput(SettingInputType.CHECKBOX, 'pyIntepreterEnabled'),
      ],
    },
  ];
}

export default function Settings() {
  const navigate = useNavigate();
  const { t, i18n } = useTranslation();
  const {
    config,
    saveConfig,
    presets,
    savePreset,
    removePreset,
    setShowSettings,
  } = useAppContext();
  const { models, fetchModels } = useInferenceContext();
  const { viewingChat } = useChatContext();
  const [tabIdx, setTabIdx] = useState(0);

  // clone the config object to prevent direct mutation
  const [localConfig, setLocalConfig] = useState<Configuration>(
    Object.assign({}, config)
  );
  const [localModels, setLocalModels] = useState<InferenceApiModel[]>(
    Object.assign([], models)
  );
  const settingTabs = useMemo<SettingTab[]>(
    () => getSettingTabsConfiguration(localConfig, localModels, t),
    [t, localConfig, localModels]
  );
  const currConv = useMemo(() => viewingChat?.conv ?? null, [viewingChat]);

  useEffect(() => {
    setShowSettings(true);

    return () => {
      setShowSettings(false);
    };
  }, [setShowSettings]);

  const { showConfirm, showAlert } = useModals();

  const onClose = useCallback(() => {
    if (currConv) navigate(`/chat/${currConv.id}`);
    else navigate('/');
  }, [currConv, navigate]);

  const resetConfig = async () => {
    if (await showConfirm('Are you sure you want to reset all settings?')) {
      setLocalConfig({ ...CONFIG_DEFAULT } as Configuration);
    }
  };

  const handleSave = async (config: Configuration) => {
    // copy the local config to prevent direct mutation
    const newConfig: Configuration = JSON.parse(JSON.stringify(config));
    // validate the config
    for (const key in newConfig) {
      if (!(key in CONFIG_DEFAULT)) continue;

      const typedKey = key as ConfigurationKey;
      const value = newConfig[typedKey];
      const defaultValue = CONFIG_DEFAULT[typedKey];
      if (isString(defaultValue)) {
        if (!isString(value)) {
          await showAlert(`Value for ${key} must be a string`);
          return;
        }
      } else if (isNumeric(defaultValue)) {
        const trimmedValue = String(value).trim();
        const numVal = Number(trimmedValue);
        if (isNaN(numVal) || !isNumeric(numVal) || trimmedValue === '') {
          await showAlert(`Value for ${key} must be numeric`);
          return;
        }
        // force conversion to number
        // @ts-expect-error this is safe
        newConfig[typedKey] = numVal as Configuration[ConfigurationKey];
      } else if (isBoolean(defaultValue)) {
        if (!isBoolean(value)) {
          await showAlert(`Value for ${key} must be boolean`);
          return;
        }
      } else {
        console.error(`Unknown default type for key ${key}`);
      }
    }
    saveConfig(newConfig);
    onClose();
  };

  const debouncedFetchModels = useDebouncedCallback(
    (newConfig: Configuration) =>
      fetchModels(newConfig, { silent: true }).then((models) =>
        setLocalModels(models)
      ),
    1000
  );

  const onChange =
    (key: ConfigurationKey) => (value: string | number | boolean) => {
      // note: we do not perform validation here, because we may get incomplete value as user is still typing it
      setLocalConfig((prevConfig) => {
        let newConfig = {
          ...prevConfig,
          [key]: value,
        };

        if (key === 'provider') {
          const typedKey = value as InferenceProvidersKey;
          const providerInfo = INFERENCE_PROVIDERS[typedKey];
          if (providerInfo?.baseUrl) {
            newConfig = {
              ...newConfig,
              baseUrl: providerInfo.baseUrl,
            };
          }
        }

        if (['provider', 'baseUrl', 'apiKey'].includes(key)) {
          debouncedFetchModels(newConfig);
        }

        return newConfig;
      });
    };

  const mapFieldToElement = (field: SettingField, idx: number) => {
    const key = `${tabIdx}-${idx}`;

    switch (field.type) {
      case SettingInputType.SHORT_INPUT:
        return (
          <SettingsModalShortInput
            key={key}
            field={field}
            value={localConfig[field.key] as string | number}
            onChange={onChange(field.key)}
          />
        );
      case SettingInputType.RANGE_INPUT:
        return (
          <SettingsModalRangeInput
            key={key}
            field={field}
            min={field.min as number}
            max={field.max as number}
            step={field.step as number}
            value={localConfig[field.key] as number}
            onChange={onChange(field.key)}
          />
        );
      case SettingInputType.LONG_INPUT:
        return (
          <SettingsModalLongInput
            key={key}
            field={field}
            value={String(localConfig[field.key])}
            onChange={onChange(field.key)}
          />
        );
      case SettingInputType.CHECKBOX:
        return (
          <SettingsModalCheckbox
            key={key}
            field={field}
            value={!!localConfig[field.key]}
            onChange={onChange(field.key)}
          />
        );
      case SettingInputType.DROPDOWN:
        return (
          <SettingsModalDropdown
            key={key}
            field={field as SettingFieldInput}
            options={(field as SettingFieldDropdown).options}
            filterable={(field as SettingFieldDropdown).filterable}
            value={String(localConfig[field.key])}
            onChange={onChange(field.key)}
          />
        );
      case SettingInputType.CUSTOM:
        switch (field.key) {
          case 'language':
            return (
              <SettingsModalDropdown
                key="language"
                field={{
                  type: SettingInputType.DROPDOWN,
                  key: 'custom',
                  translateKey: 'language',
                }}
                options={SUPPORTED_LANGUAGES.map((lang) => ({
                  value: lang.key,
                  label: lang.label,
                }))}
                value={i18n.language}
                onChange={(lang) => {
                  i18n.changeLanguage(lang as string);
                  document.documentElement.setAttribute('lang', lang as string);
                }}
              />
            );
          case 'import-export':
            return <ImportExportComponent key={key} onClose={onClose} />;
          case 'preset-manager':
            return (
              <PresetManager
                key={key}
                config={localConfig}
                onLoadConfig={handleSave}
                presets={presets}
                onSavePreset={savePreset}
                onRemovePreset={removePreset}
              />
            );
          case 'theme-manager':
            return <ThemeController key={key} />;
          case 'fetch-models':
            return (
              <Button
                key={key}
                onClick={() =>
                  fetchModels(localConfig).then((models) =>
                    setLocalModels(models)
                  )
                }
              >
                <Icon size="sm" variant="leftside">
                  <LuRefreshCw />
                </Icon>
                <Trans i18nKey="settings.actionButtons.fetchModels" />
              </Button>
            );
          default:
            if (field.component === 'delimeter') {
              return <DelimeterComponent key={key} />;
            }

            switch (typeof field.component) {
              case 'string':
              case 'number':
              case 'bigint':
              case 'boolean':
              case 'symbol':
                return (
                  <div key={key} className="mb-2">
                    {field.component}
                  </div>
                );
              default:
                return (
                  <div key={key} className="mb-2">
                    {React.createElement(field.component, {
                      value: localConfig[field.key],
                      onChange: (value: string | boolean) =>
                        onChange(field.key as ConfigurationKey)(value),
                    })}
                  </div>
                );
            }
        }
      case SettingInputType.SECTION:
        return (
          <SettingsSectionLabel key={key}>{field.label}</SettingsSectionLabel>
        );
      default:
        return null;
    }
  };

  return (
    <div className="flex flex-col h-full py-4">
      <div className="grow flex flex-col md:flex-row">
        {/* Left panel, showing sections - Desktop version */}
        <div
          className="hidden md:flex flex-col items-stretch px-4 border-r-2 border-base-200"
          role="complementary"
          aria-description="Settings sections"
          tabIndex={0}
        >
          {settingTabs.map((tab, idx) => (
            <Button
              key={idx}
              variant="ghost"
              className={classNames({
                'justify-start font-normal w-44 mb-1': true,
                'btn-active': tabIdx === idx,
              })}
              onClick={() => setTabIdx(idx)}
              dir="auto"
            >
              {tab.title}
            </Button>
          ))}
        </div>

        {/* Left panel, showing sections - Mobile version */}
        {/* This menu is skipped on a11y, otherwise it's repeated the desktop version */}
        <div
          className="md:hidden flex flex-row gap-2 mb-4 px-4"
          aria-disabled={true}
        >
          <Dropdown
            className="bg-base-200 w-full border-1 border-base-content/10 rounded-lg shadow-xs cursor-pointer p-2"
            entity="tab"
            options={settingTabs.map((tab, idx) => ({
              label: tab.title,
              value: idx,
            }))}
            currentValue={settingTabs[tabIdx].title}
            renderOption={(option) => <span>{option.label}</span>}
            isSelected={(option) => tabIdx === option.value}
            onSelect={(option) => setTabIdx(option.value as number)}
          />
        </div>

        {/* Right panel, showing setting fields */}
        <div className="grow max-h-[calc(100vh-13rem)] md:max-h-[calc(100vh-10rem)] overflow-y-auto px-6 sm:px-4">
          {settingTabs[tabIdx].fields.map(mapFieldToElement)}

          <p className="opacity-40 text-sm mt-8">
            <Trans
              i18nKey="settings.footer.version"
              values={{ version: import.meta.env.PACKAGE_VERSION }}
            />
            <br />
            <Trans i18nKey="settings.footer.storageNote" />
          </p>
        </div>
      </div>

      <div className="sticky bottom-4 flex gap-2 max-md:justify-center mt-4">
        <div className="hidden md:block w-54 h-10" />
        <Button variant="neutral" onClick={() => handleSave(localConfig)}>
          <Trans i18nKey="settings.actionButtons.saveBtnLabel" />
        </Button>
        <Button onClick={onClose}>
          <Trans i18nKey="settings.actionButtons.cancelBtnLabel" />
        </Button>
        <Button onClick={resetConfig}>
          <Trans i18nKey="settings.actionButtons.resetBtnLabel" />
        </Button>
      </div>
    </div>
  );
}

// src/routes/settings/+page.svelte
<script lang="ts">
  import { _ } from 'svelte-i18n';
  import { goto } from '$app/navigation';
  import { CONFIG_DEFAULT, INFERENCE_PROVIDERS } from '$lib/config';
  import { app } from '$lib/state/app.svelte';
  import { inference } from '$lib/state/inference.svelte';
  import { modal } from '$lib/state/modal.svelte';
  import { toast } from '$lib/components/toast.js';
  import Button from '$lib/components/Button.svelte';
  import type {
    Configuration,
    ConfigurationKey,
    InferenceApiModel,
    InferenceProvidersKey,
  } from '$lib/types';
  import { isBoolean, isNumeric, isString } from '$lib/utils/type-guards';
  import GeneralTab from './GeneralTab.svelte';
  import UITab from './UITab.svelte';
  import VoiceTab from './VoiceTab.svelte';
  import ConversationsTab from './ConversationsTab.svelte';
  import PresetsTab from './PresetsTab.svelte';
  import ImportExportTab from './ImportExportTab.svelte';
  import AdvancedTab from './AdvancedTab.svelte';
  import ExperimentalTab from './ExperimentalTab.svelte';

  const tabs = [
    { id: 'general', label: 'settings.tabs.general', default: 'General' },
    { id: 'ui', label: 'settings.tabs.ui', default: 'UI' },
    { id: 'voice', label: 'settings.tabs.voice', default: 'Voice' },
    { id: 'conversations', label: 'settings.tabs.conversations', default: 'Conversations' },
    { id: 'presets', label: 'settings.tabs.presets', default: 'Presets' },
    { id: 'import-export', label: 'settings.tabs.importExport', default: 'Import / Export' },
    { id: 'advanced', label: 'settings.tabs.advanced', default: 'Advanced' },
    { id: 'experimental', label: 'settings.sections.experimental', default: 'Experimental' },
  ];

  let tabId = $state('general');
  let localConfig = $state<Configuration>({ ...app.config });
  let localModels = $state<InferenceApiModel[]>([...inference.models]);

  function onchange(key: ConfigurationKey) {
    return (value: string | number | boolean) => {
      let next = { ...localConfig, [key]: value };
      if (key === 'provider') {
        const info = INFERENCE_PROVIDERS[value as InferenceProvidersKey];
        if (info?.baseUrl) next = { ...next, baseUrl: info.baseUrl };
      }
      localConfig = next;
      if (['provider', 'baseUrl', 'apiKey'].includes(key)) {
        debouncedFetch(next);
      }
    };
  }

  let _fetchTimer: ReturnType<typeof setTimeout>;
  function debouncedFetch(config: Configuration) {
    clearTimeout(_fetchTimer);
    _fetchTimer = setTimeout(async () => {
      const models = await inference.fetchModels(config, { silent: true });
      localModels = models;
    }, 1000);
  }

  async function fetchModels() {
    localModels = await inference.fetchModels(localConfig);
  }

  async function handleSave() {
    const cfg: Configuration = JSON.parse(JSON.stringify(localConfig));
    for (const key in cfg) {
      if (!(key in CONFIG_DEFAULT)) continue;
      const k = key as ConfigurationKey;
      const val = cfg[k];
      const def = CONFIG_DEFAULT[k];
      if (isString(def)) {
        if (!isString(val)) { await modal.showAlert(`Value for ${key} must be a string`); return; }
      } else if (isNumeric(def)) {
        const n = Number(String(val).trim());
        if (isNaN(n)) { await modal.showAlert(`Value for ${key} must be numeric`); return; }
        // @ts-expect-error safe cast
        cfg[k] = n;
      } else if (isBoolean(def)) {
        if (!isBoolean(val)) { await modal.showAlert(`Value for ${key} must be boolean`); return; }
      }
    }
    app.saveConfig(cfg);
    handleClose();
  }

  async function handleReset() {
    if (await modal.showConfirm('Are you sure you want to reset all settings?')) {
      localConfig = { ...CONFIG_DEFAULT } as Configuration;
    }
  }

  function handleClose() {
    const conv = inference.selectedModel; // just checking if we have context
    void conv;
    goto('/');
  }

  async function handleSavePreset(name: string, config: Configuration) {
    await app.savePreset(name, config, toast.success);
  }

  async function handleRemovePreset(name: string) {
    await app.removePreset(name, toast.success);
  }
</script>

<svelte:head>
  <title>Settings — llama.ui</title>
</svelte:head>

<div class="settings-page">
  <!-- Tab sidebar (desktop) / tab bar (mobile) -->
  <nav class="settings-tabs" role="tablist" aria-label="Settings sections">
    {#each tabs as tab (tab.id)}
      <button
        type="button"
        role="tab"
        class="settings-tabs__btn"
        class:settings-tabs__btn--active={tabId === tab.id}
        aria-selected={tabId === tab.id}
        onclick={() => (tabId = tab.id)}
      >
        {$_(tab.label, { default: tab.default })}
      </button>
    {/each}
  </nav>

  <!-- Tab content -->
  <div class="settings-content">
    {#if tabId === 'general'}
      <GeneralTab config={localConfig} models={localModels} {onchange} onfetchmodels={fetchModels} />
    {:else if tabId === 'ui'}
      <UITab config={localConfig} {onchange} />
    {:else if tabId === 'voice'}
      <VoiceTab config={localConfig} {onchange} />
    {:else if tabId === 'conversations'}
      <ConversationsTab config={localConfig} {onchange} />
    {:else if tabId === 'presets'}
      <PresetsTab config={localConfig} presets={app.presets} onsavepreset={handleSavePreset} onremovepreset={handleRemovePreset} onsaveconfig={async (c) => { app.saveConfig(c); handleClose(); }} />
    {:else if tabId === 'import-export'}
      <ImportExportTab onclose={handleClose} />
    {:else if tabId === 'advanced'}
      <AdvancedTab config={localConfig} {onchange} />
    {:else if tabId === 'experimental'}
      <ExperimentalTab config={localConfig} {onchange} />
    {/if}

    <footer class="settings-footer">
      <p>v{import.meta.env.PACKAGE_VERSION ?? ''} · {$_('settings.footer.storageNote', { default: 'All data stored locally.' })}</p>
    </footer>
  </div>

  <!-- Action bar -->
  <div class="settings-actions">
    <Button variant="neutral" onclick={handleSave}>{$_('settings.actionButtons.saveBtnLabel')}</Button>
    <Button onclick={handleClose}>{$_('settings.actionButtons.cancelBtnLabel')}</Button>
    <Button variant="ghost" onclick={handleReset}>{$_('settings.actionButtons.resetBtnLabel')}</Button>
  </div>
</div>

<style>
  .settings-page {
    display: grid;
    grid-template-rows: 1fr auto;
    grid-template-columns: 1fr;
    height: 100%;
    overflow: hidden;
  }

  @media (min-width: 768px) {
    .settings-page {
      grid-template-columns: 11rem 1fr;
      grid-template-rows: 1fr auto;
    }
  }

  .settings-tabs {
    display: flex;
    flex-direction: row;
    overflow-x: auto;
    gap: 0.25rem;
    padding: 0.5rem;
    border-bottom: 1px solid var(--color-border);
  }

  @media (min-width: 768px) {
    .settings-tabs {
      flex-direction: column;
      overflow-x: hidden;
      border-bottom: none;
      border-right: 1px solid var(--color-border);
      padding: 1rem 0.5rem;
    }
  }

  .settings-tabs__btn {
    background: none;
    border: none;
    border-radius: var(--radius-md);
    padding: 0.375rem 0.75rem;
    cursor: pointer;
    color: var(--color-text);
    font-size: 0.875rem;
    text-align: left;
    white-space: nowrap;
    flex-shrink: 0;
    transition: background 0.15s;
  }

  .settings-tabs__btn:hover { background: var(--color-surface-alt); }
  .settings-tabs__btn--active { background: var(--color-surface-alt); font-weight: 600; }

  .settings-content {
    overflow-y: auto;
    padding: 1rem 1.5rem;
    grid-column: 1;
    grid-row: 1;
  }

  @media (min-width: 768px) {
    .settings-content { grid-column: 2; }
  }

  .settings-footer {
    font-size: 0.75rem;
    color: var(--color-text-muted);
    margin-top: 2rem;
    padding-top: 0.75rem;
    border-top: 1px solid var(--color-border);
  }

  .settings-actions {
    display: flex;
    gap: 0.5rem;
    padding: 0.75rem 1rem;
    border-top: 1px solid var(--color-border);
    background: var(--color-bg);
    justify-content: center;
    grid-column: 1 / -1;
  }
</style>
